#!/usr/bin/env python3
"""
inject-jsonld.py — Idempotent JSON-LD + BreadcrumbList injector
================================================================
Walks every index.html under the repo and injects an autogenerated
JSON-LD block (SoftwareApplication / CollectionPage / WebPage +
BreadcrumbList) immediately before </head>.

Skips:
  - 404.html  (canonical points to homepage; not a real entity)
  - under-construction.html  (noindex)
  - homepage index.html  (already has a curated WebSite + Organization graph)
  - search/index.html  (already has a curated WebPage + SearchAction)

Idempotent: any block delimited by AUTOGEN:JSONLD markers is replaced
on subsequent runs.  Existing non-autogen JSON-LD blocks are left alone.

Usage:
    python3 scripts/inject-jsonld.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://glee-fully.tools"
SKIP_DIRS = {"node_modules", ".local", ".git", "attached_assets", "assets"}
SKIP_FILES = {Path("index.html"), Path("404.html"), Path("under-construction.html"),
              Path("search/index.html")}

START = "<!-- AUTOGEN:JSONLD -->"
END = "<!-- /AUTOGEN:JSONLD -->"

# ---------------------------------------------------------------------------
# Branch and tool-ette label tables (drives breadcrumb names + JSON-LD names)
# ---------------------------------------------------------------------------
BRANCH_LABELS = {
    "01-discovered-careers": "Discovered Careers",
    "02-treasured-finds":    "Treasured Finds",
    "03-tasty-tracker":      "Tasty Tracker",
    "04-travelers-guide":    "Travelers Guide",
    "05-organized-life":     "Organized Life",
    "06-healthy-bee-ing":    "Healthy Bee-ing",
    "07-identity-known":     "Identity Known",
}

SUPPORT_LABELS = {
    "about":    "About",
    "contact":  "Contact",
    "ecosystem":"Ecosystem",
    "legal":    "Legal",
    "persona":  "Personas",
    "universe": "Universe",
    "toolbox":  "Toolbox",
}


# ---------------------------------------------------------------------------
def read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def first_match(pattern: str, text: str, group: int = 1) -> str | None:
    m = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    return m.group(group) if m else None


def extract_meta(html: str) -> dict:
    """Pull the bits we need to compose JSON-LD from existing <head>."""
    title = first_match(r"<title[^>]*>(.*?)</title>", html) or ""
    desc = first_match(r'<meta\s+name="description"\s+content="([^"]*)"', html) or ""
    canonical = first_match(r'<link\s+rel="canonical"\s+href="([^"]+)"', html) or ""
    og_image = first_match(r'<meta\s+property="og:image"\s+content="([^"]+)"', html) or ""
    og_image_width = first_match(r'<meta\s+property="og:image:width"\s+content="([^"]+)"', html) or ""
    og_image_height = first_match(r'<meta\s+property="og:image:height"\s+content="([^"]+)"', html) or ""
    og_image_alt = first_match(r'<meta\s+property="og:image:alt"\s+content="([^"]*)"', html) or ""
    keywords = first_match(r'<meta\s+name="keywords"\s+content="([^"]*)"', html) or ""
    return {
        "title": title.strip().replace("\n", " "),
        "description": desc.strip(),
        "canonical": canonical.strip(),
        "og_image": og_image.strip(),
        "og_image_width": og_image_width.strip(),
        "og_image_height": og_image_height.strip(),
        "og_image_alt": og_image_alt.strip(),
        "keywords": keywords.strip(),
    }


def short_title(title: str) -> str:
    """Strip the ' — Glee-fully Personalizable Tools™ ...' suffix."""
    return re.split(r"\s+[—\-–]\s+Glee", title, maxsplit=1)[0].strip()


def crumbs_for(rel_path: Path) -> list[tuple[str, str]]:
    """Return [(name, url), …] for the breadcrumb trail of this page."""
    parts = rel_path.parts[:-1]  # drop 'index.html'
    crumbs: list[tuple[str, str]] = [("Home", f"{SITE}/")]
    cur = ""
    for i, seg in enumerate(parts):
        cur += f"{seg}/"
        if seg == "toolbox":
            label = "Toolbox"
        elif seg in BRANCH_LABELS:
            label = BRANCH_LABELS[seg]
        elif seg in SUPPORT_LABELS:
            label = SUPPORT_LABELS[seg]
        else:
            # Tool-ette folder like '01a-resume-builder' → 'Resume Builder'
            label = re.sub(r"^\d+[a-z]?-", "", seg).replace("-", " ").title()
            # Special-case branded names
            label = label.replace("Blinkin", "bLinkIn").replace("Bee Ing", "Bee-ing")
        crumbs.append((label, f"{SITE}/{cur}"))
    return crumbs


def page_kind(rel_path: Path) -> str:
    """Classify the page so we know which JSON-LD @type to use.

    Path layouts (relative to repo root):
      toolbox/index.html                                  → toolbox-hub
      toolbox/0N-branch/index.html                        → branch-hub
      toolbox/0N-branch/0Nx-tool/index.html               → tool-ette
      <anything else>/index.html                          → supporting
    """
    parts = rel_path.parts
    # tool-ette is 4 segments: toolbox / 0N-branch / 0Nx-tool / index.html
    if (len(parts) == 4 and parts[0] == "toolbox"
            and re.match(r"^\d+[a-z]-", parts[2])):
        return "tool-ette"
    if len(parts) == 2 and parts[0] == "toolbox":
        return "toolbox-hub"
    if (len(parts) == 3 and parts[0] == "toolbox"
            and re.match(r"^\d+-", parts[1])):
        return "branch-hub"
    return "supporting"


def build_jsonld(rel_path: Path, meta: dict) -> str:
    """Build the JSON-LD payload appropriate for this page kind."""
    kind = page_kind(rel_path)
    name = short_title(meta["title"]) or rel_path.parent.name
    desc = meta["description"]
    canonical = meta["canonical"] or f"{SITE}/{'/'.join(rel_path.parts[:-1])}/"
    image = meta["og_image"]
    image_obj: dict | None = None
    if image:
        image_obj = {"@type": "ImageObject", "url": image}
        if meta["og_image_width"]:
            image_obj["width"] = int(meta["og_image_width"])
        if meta["og_image_height"]:
            image_obj["height"] = int(meta["og_image_height"])
        if meta["og_image_alt"]:
            image_obj["caption"] = meta["og_image_alt"]
    crumbs = crumbs_for(rel_path)

    breadcrumb_id = canonical + "#breadcrumb"
    breadcrumb_node = {
        "@type": "BreadcrumbList",
        "@id": breadcrumb_id,
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
            for i, (n, u) in enumerate(crumbs)
        ],
    }

    if kind == "tool-ette":
        node = {
            "@type": "SoftwareApplication",
            "@id": canonical + "#software",
            "name": name,
            "url": canonical,
            "description": desc,
            "applicationCategory": "ProductivityApplication",
            "operatingSystem": "Web",
            "isAccessibleForFree": True,
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
            "creator": {"@type": "Organization", "name": "Glee-fully Personalizable Tools™",
                        "url": f"{SITE}/"},
            "isPartOf": {"@type": "WebSite", "url": f"{SITE}/",
                         "name": "Glee-fully Personalizable Tools™"},
        }
        if image_obj:
            node["image"] = image_obj
        if meta["keywords"]:
            node["keywords"] = meta["keywords"]
    elif kind in ("branch-hub", "toolbox-hub"):
        node = {
            "@type": "CollectionPage",
            "@id": canonical + "#collection",
            "name": name,
            "url": canonical,
            "description": desc,
            "isPartOf": {"@type": "WebSite", "url": f"{SITE}/",
                         "name": "Glee-fully Personalizable Tools™"},
        }
        if image_obj:
            node["primaryImageOfPage"] = image_obj
    else:  # supporting
        node = {
            "@type": "WebPage",
            "@id": canonical + "#webpage",
            "name": name,
            "url": canonical,
            "description": desc,
            "isPartOf": {"@type": "WebSite", "url": f"{SITE}/",
                         "name": "Glee-fully Personalizable Tools™"},
        }
        if image_obj:
            node["primaryImageOfPage"] = image_obj

    # BreadcrumbList is a top-level @graph node (referenced by @id from the main node),
    # so Google can evaluate it independently for breadcrumb rich results.
    node["breadcrumb"] = {"@id": breadcrumb_id}
    payload = {"@context": "https://schema.org", "@graph": [node, breadcrumb_node]}
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (f"    {START}\n"
            f"    <script type=\"application/ld+json\">\n"
            f"{body}\n"
            f"    </script>\n"
            f"    {END}")


def inject(html: str, block: str) -> str:
    """Replace existing AUTOGEN block (including its leading indent), else
    insert before </head>.  The regex consumes leading whitespace on the line
    so re-runs do not accumulate extra indent."""
    rgx = re.compile(r"[ \t]*" + re.escape(START) + r".*?" + re.escape(END),
                     re.DOTALL)
    if rgx.search(html):
        return rgx.sub(block, html)
    return re.sub(r"(\s*)</head>", f"\n{block}\n\\1</head>", html, count=1)


def main() -> int:
    rel_skip = {p.as_posix() for p in SKIP_FILES}
    edited = 0
    skipped = 0
    for path in sorted(ROOT.rglob("index.html")):
        rel = path.relative_to(ROOT)
        if any(s in rel.parts for s in SKIP_DIRS):
            continue
        if rel.as_posix() in rel_skip:
            skipped += 1
            continue
        html = read(path)
        meta = extract_meta(html)
        if not meta["canonical"]:
            print(f"  ! skip (no canonical): {rel}")
            skipped += 1
            continue
        block = build_jsonld(rel, meta)
        new_html = inject(html, block)
        if new_html != html:
            path.write_text(new_html, encoding="utf-8")
            edited += 1
            print(f"  + {rel}")
    # Also handle 404 + under-construction explicitly?  No — keep them out.
    print(f"\nDone. Edited {edited} file(s); skipped {skipped} curated file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
